apiVersion: v1
kind: Service
metadata:
  name: usermgmt-service
  labels: 
    app: usermgmt-app
spec:
  type: LoadBalancer
  selector:
    app: usermgmt-app
  ports:
    - port: 80
      targetPort: 8095
     
  